[package]
name = "diagram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
proc-macro2 = { version = "1.0.82", features = ["span-locations"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
syn = { version = "2.0.64", features = ["full", "extra-traits"] }
tinytemplate = "1.2.1"
uuid = { version = "1.8.0", features = ["v4"] }
walkdir = "2.5.0"
